global using FluentAssertions;
global using Moq;
global using RentalMVC.Domain.Model.Entity.UserEntities;
global using Xunit;
global using static RentalMVC.Tests.SampleData.AddressSample.AddressSample;
global using static RentalMVC.Tests.SampleData.ClientSample.ClientSample;
global using static RentalMVC.Tests.SampleData.ContectDataSample.ContactDataSample;
global using static RentalMVC.Tests.SampleData.DateTimeSample;
global using static RentalMVC.Tests.SampleData.DeviceSample.DeviceSample;
global using static RentalMVC.Tests.SampleData.DeviceSample.VMs.DeviceExtendedVmSample;
global using static RentalMVC.Tests.SampleData.DeviceSample.VMs.NewDeviceVmSample;
global using static RentalMVC.Tests.SampleData.DeviceSample.VMs.DeviceVmSample;
global using static RentalMVC.Tests.SampleData.DeviceSample.VMs.EditDeviceVmSample;
global using static RentalMVC.Tests.SampleData.DeviceSample.VMs.ListDeviceVmSample;
global using static RentalMVC.Tests.SampleData.DeviceTypeSample.DeviceTypeSample;
global using static RentalMVC.Tests.SampleData.DeviceTypeSample.VMs.ListDeviceTypeVmSample;
global using static RentalMVC.Tests.SampleData.DeviceTypeSample.VMs.DeviceTypeVmSample;
global using static RentalMVC.Tests.SampleData.EmployeeSample.EmployeeSample;
global using static RentalMVC.Tests.SampleData.LessorSample.LessorSample;
global using static RentalMVC.Tests.SampleData.NodeSample.NodeSample;
global using static RentalMVC.Tests.SampleData.RentalSample.RentalSample;
global using static RentalMVC.Tests.SampleData.UserDetailSample.UserDetailSample;
global using static RentalMVC.Tests.SampleData.ReservationSample.ReservationSample;
global using static RentalMVC.Tests.SampleData.ReservationSample.ReservationPositionVMs.ListPositionVmSample;
global using static RentalMVC.Tests.SampleData.ReservationSample.ReservationPositionVMs.PositionVmSample;

