using RentalMVC.Domain.Model.Entity.DeviceEntities;

namespace RentalMVC.Tests.SampleData.DeviceSample;

internal class DeviceSample
{
    public static Device NewDevice => new()
    {
        CreatorId = "",
        Name = "",
        SerialNr = "",
        DeviceType = NewDeviceType,
        Rental = NewRental
    };
    public static Device[] GetModifiedDeviceSample =>
        new Device[7] 
        {
            new()
            {
                Id = 12,
                Name = "Makita DT4",
                DeviceTypeId = 4,
                RentalId = 2,
                SerialNr = "44-xx-cc",
                CreatorId = Users.Lessor_007.GetUserId(),
                IsAvailable = true,
                Active = true,
                CreatedAt = GetDateTimeSample[13],
                DeviceType = NewDeviceType,
                Rental = NewRental,
                ModifiedAt = GetModifiedDateTimeSample[14],
                ModifierId = Users.Lessor_007.GetUserId(),
                
            },
            new()
            {
                Id = 13,
                Name = "Bosh WZR",
                DeviceTypeId = 4,
                RentalId = 2,
                SerialNr = "33hjurc",
                CreatorId = Users.Lessor_007.GetUserId(),
                IsAvailable = true,
                Active = true,
                CreatedAt = GetDateTimeSample[13],
                IndividualPrice = 50,
                Description = "150kg",
                ModifiedAt = GetModifiedDateTimeSample[15],
                ModifierId = Users.Lessor_007.GetUserId(),
                DeviceType = NewDeviceType,
                Rental = NewRental,
            },
            new()
            {
                Id = 14,
                Name = "SomeCompany 443dc",
                DeviceTypeId = 4,
                RentalId = 2,
                SerialNr = "445ghj",
                CreatorId = Users.Lessor_007.GetUserId(),
                IsAvailable = true,
                Active = true,
                CreatedAt = GetDateTimeSample[13],
                IndividualPrice = 30,
                Description = "50kg",
                ModifiedAt = GetModifiedDateTimeSample[16],
                ModifierId = Users.Lessor_007.GetUserId(),
                DeviceType = NewDeviceType,
                Rental = NewRental,
            },
            new()
            {
                CreatorId = Users.Lessor_006.GetUserId(),
                CreatedAt = GetDateTimeSample[0],
                Id = 1,
                Active = false,
                Name = "Wiertarka modyfikowana",
                DeviceTypeId = 1,
                RentalId = 1,
                SerialNr = "TO-JEST-1234",
                IsAvailable = true,
                IndividualPrice = 0,
                Description = "Ta wiertarka jest niekatywna i ma zredukowaną cenę",
                DeviceType = NewDeviceType,
                Rental = NewRental,
                ModifiedAt = GetModifiedDateTimeSample[17],
                ModifierId = Users.Employee_008.GetUserId(),
            },
            new ()
            {
                CreatorId = Users.Lessor_006.GetUserId(),
                CreatedAt = GetDateTimeSample[1],
                Id = 2,
                Active = true,
                IsAvailable = true,
                Name = "zmieniono typ, usunieto opis, dodano cenę",
                DeviceTypeId = 2,
                RentalId = 1,
                SerialNr = "TO-JEST-BOSz",
                Description = "",
                IndividualPrice = 11,
                DeviceType= NewDeviceType,
                Rental = NewRental,
                ModifiedAt = GetModifiedDateTimeSample[18],
                ModifierId = Users.Employee_008.GetUserId(),
            },
            new()
            {
                CreatorId = Users.Lessor_006.GetUserId(),
                CreatedAt = GetDateTimeSample[2],
                Id = 3,
                Name = "Wiertarka dobra",
                DeviceTypeId = 1,
                RentalId = 1,
                SerialNr = "TO-Kijowe-JEST",
                Active = true,
                Description = "Dostaje opis i jest aktywna",
                ModifiedAt = GetModifiedDateTimeSample[19],
                ModifierId = Users.Employee_008.GetUserId(),
                DeviceType= NewDeviceType,
                Rental = NewRental,
            },
            new()
            {
                CreatorId = Users.Lessor_006.GetUserId(),
                CreatedAt = GetDateTimeSample[2],
                Id = 3,
                Name = "ten obiekt ma zmienione pole dostępności",
                DeviceTypeId = 1,
                RentalId = 1,
                SerialNr = "TO-Kijowe-JEST",
                Active = true,
                ModifiedAt = GetModifiedDateTimeSample[19],
                ModifierId = Users.Employee_008.GetUserId(),
                DeviceType= NewDeviceType,
                Rental = NewRental,
            },
        };
    public static Device[] GetDeletedDeviceSample =>
        new Device[3]
        {
            new()
            {
                Name = "model modyfikowany do usunieca",
                DeviceTypeId = 1,
                RentalId = 1,
                SerialNr = "model przeszedł walicację",
                CreatorId = Users.Lessor_006.GetUserId(),
                DeviceType= NewDeviceType,
                Rental= NewRental,
                Id = 8,
                CreatedAt = GetDateTimeSample[3],
                IndividualPrice = 6,
                Description = "dostepny i aktywny",
                ModifiedAt = GetDateTimeSample[6],
                ModifierId = Users.Employee_008.GetUserId(),
                DeletedAt = GetDateTimeSample[6],
                DeletedBy = Users.Employee_008.GetUserId(),
                IsAvailable = false,
                Active = false,  
                Deleted = true
            },
            new()
            {
                Id = 9,
                Name = "model pełny do usuniecia",
                DeviceTypeId = 1,
                RentalId = 1,
                SerialNr = "model przeszedł walicację",
                CreatorId = Users.Lessor_006.GetUserId(),
                DeviceType= NewDeviceType,
                Rental= NewRental,
                IsAvailable = false,
                Active = false,
                CreatedAt = GetDateTimeSample[3],
                IndividualPrice = 6,
                Description = "dostepny i aktywny",
                DeletedAt = GetDateTimeSample[5],
                ModifiedAt = GetDateTimeSample[5],
                DeletedBy = Users.Employee_008.GetUserId(),
                ModifierId = Users.Employee_008.GetUserId(),
                Deleted = true
            },
            new()
            {
                Id = 10,
                Name = "model uproszczony do usuniecia",
                DeviceTypeId = 2,
                RentalId = 1,
                SerialNr = "model przeszedł walicację",
                CreatorId = Users.Lessor_006.GetUserId(),
                DeviceType= NewDeviceType,
                Rental= NewRental,
                IsAvailable = false,
                Active = false,
                CreatedAt = GetDateTimeSample[3],
                DeletedAt = GetDateTimeSample[5],
                DeletedBy = Users.Lessor_006.GetUserId(),
                Deleted = true,
                ModifierId = Users.Lessor_006.GetUserId(),
                ModifiedAt = GetDateTimeSample[5],                    
            }
        };
    public static Device[] GetDevicesSample =>
            new Device[17]
            {
                new()
                {
                    CreatorId = Users.Lessor_006.GetUserId(),
                    CreatedAt = GetDateTimeSample[0],
                    Id = 1,
                    Active = true,
                    Name = "Wiertarka Makita Suuper Turbo",
                    DeviceType = NewDeviceType,
                    DeviceTypeId = 1,
                    Rental = NewRental,
                    RentalId = 1,
                    SerialNr = "TO-JEST-NUMER-1234",
                    IsAvailable = true,
                    IndividualPrice = 11,
                    Description = "Ta wiertarka jest droższa",
                    Deleted = false,
                    Positions = null,                    
                },

                new ()
                {
                    CreatorId = Users.Lessor_006.GetUserId(),
                    CreatedAt = GetDateTimeSample[1],
                    Id = 2,
                    Active = true,
                    IsAvailable = true,
                    Name = "Wiertarka Bosz Super",
                    DeviceType= NewDeviceType,
                    DeviceTypeId = 1,
                    Rental = NewRental,
                    RentalId = 1,
                    SerialNr = "TO-JEST-BOSz",
                    Description = "Ta wiertarka jest standardowa",
                },
                new()
                {
                    CreatorId = Users.Lessor_006.GetUserId(),
                    CreatedAt = GetDateTimeSample[2],
                    Id = 3,
                    Name = "Wiertarka uduś",
                    DeviceType= NewDeviceType,
                    DeviceTypeId = 1,
                    Rental = NewRental,
                    RentalId = 1,
                    SerialNr = "TO-Kijowe-JEST",
                },
                new()
                {
                    CreatorId = Users.Lessor_006.GetUserId(),
                    CreatedAt = GetDateTimeSample[2],
                    Id = 4,
                    Active = true,
                    IsAvailable = true,
                    Name = "Zepsuta wiertarka",
                    DeviceType= NewDeviceType,
                    DeviceTypeId = 1,
                    Rental = NewRental,
                    RentalId = 1,
                    SerialNr = "TO-Kijowe-JEST",
                    Deleted = true,
                    DeletedAt = GetDateTimeSample[2],
                    DeletedBy = Users.Lessor_006.GetUserId(),
                },
                new()
                {
                    CreatorId = Users.Lessor_006.GetUserId(),
                    CreatedAt = GetDateTimeSample[2],
                    Id = 5,
                    Active = true,
                    IsAvailable = true,
                    Name = "rental id is diffrent",
                    DeviceType= NewDeviceType,
                    DeviceTypeId = 1,
                    Rental = NewRental,
                    RentalId = 2,
                    SerialNr = "not deleted"
                },
                new()
                {
                    Description = "pełny obiekt",
                    Name = "New Device z id 1",
                    SerialNr = "dla typu młotek z id typu =2",
                    DeviceTypeId = 2,
                    IndividualPrice = 4,
                    RentalId = 1,
                    CreatorId = Users.Lessor_006.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental = NewRental,
                    Active = true,
                    CreatedAt= GetDateTimeSample[3],
                    IsAvailable = true,
                    Id = 6,                    
                },
                new()
                {
                    Name = "model uproszczony",
                    DeviceTypeId = 2,
                    RentalId = 1,
                    SerialNr = "model przeszedł walicację",
                    CreatorId = Users.Lessor_006.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    Id = 7,
                    IsAvailable = false,
                    Active = false,
                    CreatedAt = GetDateTimeSample[3],                
                },
                new()
                {
                    Name = "model modyfikowany do usunieca",
                    DeviceTypeId = 1,
                    RentalId = 1,
                    SerialNr = "model przeszedł walicację",
                    CreatorId = Users.Lessor_006.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    Id = 8,
                    IsAvailable = true,
                    Active = true,
                    CreatedAt = GetDateTimeSample[3], 
                    IndividualPrice = 6,
                    Description = "dostepny i aktywny",
                    ModifiedAt = GetDateTimeSample[4],
                    ModifierId = Users.Employee_008.GetUserId(),
                },
                new()
                {
                    Id = 9,
                    Name = "model pełny do usuniecia",
                    DeviceTypeId = 1,
                    RentalId = 1,
                    SerialNr = "model przeszedł walicację",
                    CreatorId = Users.Lessor_006.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    IsAvailable = false,
                    Active = false,
                    CreatedAt = GetDateTimeSample[3], 
                    IndividualPrice = 6,
                    Description = "dostepny i aktywny",                   
                },
                new()
                {
                    Id = 10,
                    Name = "model uproszczony do usuniecia",
                    DeviceTypeId = 2,
                    RentalId = 1,
                    SerialNr = "model przeszedł walicację",
                    CreatorId = Users.Lessor_006.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    IsAvailable = false,
                    Active = false,
                    CreatedAt = GetDateTimeSample[3],
                                      
                },
                new()
                {
                    Description = "pełny obiekt niekatywny",
                    Name = "New Device z rental id 1",
                    SerialNr = "dla typu młotek z id typu =2",
                    DeviceTypeId = 2,
                    IndividualPrice = 4,
                    RentalId = 1,
                    CreatorId = Users.Employee_008.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental = NewRental,
                    Active = false,
                    CreatedAt= GetDateTimeSample[3],
                    IsAvailable = false,
                    Id = 11,
                },
                new()
                {
                    Name = "Makita DT4",
                    DeviceTypeId = 4,
                    RentalId = 2,
                    SerialNr = "44-xx-cc",
                    CreatorId = Users.Lessor_007.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    IsAvailable = true,
                    Active = true,
                    CreatedAt = GetDateTimeSample[13],
                    Id = 12,
                },
                new()
                {
                    Name = "Bosh WZR",
                    DeviceTypeId = 4,
                    RentalId = 2,
                    SerialNr = "33hjurc",
                    CreatorId = Users.Lessor_007.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    IsAvailable = true,
                    Active = true,
                    CreatedAt = GetDateTimeSample[13],
                    IndividualPrice = 50,
                    Description = "150kg",
                    ModifiedAt = GetModifiedDateTimeSample[13],
                    ModifierId = Users.Lessor_007.GetUserId(),
                    Id = 13,
                },
                new()
                {
                    Id = 14,
                    Name = "SomeCompany 443dc",
                    DeviceTypeId = 4,
                    RentalId = 2,
                    SerialNr = "445ghj",
                    CreatorId = Users.Lessor_007.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    IsAvailable = true,
                    Active = true,
                    CreatedAt = GetDateTimeSample[13],
                    IndividualPrice = 30,
                    Description = "50kg",
                },
                new()
                {
                    Id = 15,
                    Name = "Wiertnica ręczna 5kg",
                    DeviceTypeId = 5,
                    RentalId = 2,
                    SerialNr = "6634",
                    CreatorId = Users.Lessor_007.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    IsAvailable = false,
                    Active = true,
                    CreatedAt = GetDateTimeSample[14],
                    IndividualPrice = 10,
                },
                new()
                {
                    Id = 16,
                    Name = "WIERTNICA SPALINOWA ŚWIDER DO ZIEMI",
                    DeviceTypeId = 5,
                    RentalId = 2,
                    SerialNr = "GD-520",
                    CreatorId = Users.Lessor_007.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    IsAvailable = false,
                    Active = true,
                    CreatedAt = GetDateTimeSample[14],
                    Description = "14kg, 5,2 KM",
                },
                new()
                {
                    Id = 17,
                    Name = "Test dla Rental2 i type 5",
                    DeviceTypeId = 5,
                    RentalId = 2,
                    SerialNr = "GD-520",
                    CreatorId = Users.Lessor_007.GetUserId(),
                    DeviceType= NewDeviceType,
                    Rental= NewRental,
                    IsAvailable = true,
                    Active = false,
                    CreatedAt = GetDateTimeSample[14],
                    Description = "Dane nie poprawne",
                },
            };

}
